import assert from "node:assert/strict";

import { buildMarkdownReport } from "../static/adhd-report.mjs";
import { scoreScreening } from "../static/adhd-scoring.mjs";

function buildBaseResponses(value) {
  return {
    safetyImmediateRisk: "no",
    attentionSustain: value,
    attentionTrack: value,
    attentionOrganize: value,
    attentionForget: value,
    attentionStart: value,
    attentionFinish: value,
    attentionTime: value,
    attentionDeadline: value,
    attentionItems: value,
    attentionEffort: value,
    restlessnessInternal: value,
    restlessnessFidget: value,
    restlessnessWait: value,
    restlessnessInterrupt: value,
    restlessnessImpulse: value,
    restlessnessConsequences: value,
    restlessnessTalk: value,
    impairmentWork: value,
    impairmentHome: value,
    impairmentFinances: value,
    impairmentRelationships: value,
    impairmentTime: value,
    impairmentProjects: value,
    impairmentHealth: value,
    impairmentSafety: value,
    childhoodItems: value > 3 ? 3 : value,
    childhoodHomework: value > 3 ? 3 : value,
    childhoodTeacher: value > 3 ? 3 : value,
    childhoodSupervision: value > 3 ? 3 : value,
    childhoodDisorganization: value > 3 ? 3 : value,
    childhoodInterrupt: value > 3 ? 3 : value,
    childhoodUneven: value > 3 ? 3 : value,
    crossSettings: [],
    overlappingFactors: [],
  };
}

function testLowSignal() {
  const responses = buildBaseResponses(0);
  const result = scoreScreening(responses);
  assert.equal(result.signal.label, "Low ADHD-related screening signal");
}

function testElevatedSignal() {
  const responses = buildBaseResponses(4);
  responses.crossSettings = ["Work or school", "Home responsibilities", "Relationships"];
  const result = scoreScreening(responses);
  assert.equal(result.signal.label, "Elevated ADHD-related screening signal");
}

function testNoElevatedWithoutImpairment() {
  const responses = buildBaseResponses(4);
  responses.impairmentWork = 0;
  responses.impairmentHome = 0;
  responses.impairmentFinances = 0;
  responses.impairmentRelationships = 0;
  responses.impairmentTime = 0;
  responses.impairmentProjects = 0;
  responses.impairmentHealth = 0;
  responses.impairmentSafety = 0;
  responses.crossSettings = ["Work or school", "Home responsibilities", "Relationships"];
  const result = scoreScreening(responses);
  assert.notEqual(result.signal.label, "Elevated ADHD-related screening signal");
}

function testOverlapCaution() {
  const responses = buildBaseResponses(4);
  responses.crossSettings = ["Work or school", "Home responsibilities", "Relationships"];
  responses.overlappingFactors = [
    "Insufficient sleep",
    "Anxiety symptoms",
    "Depressive symptoms",
    "Major burnout or chronic stress",
    "Substance use including cannabis, alcohol, non-prescribed stimulants, or sedatives",
  ];
  const result = scoreScreening(responses);
  assert.equal(result.signal.label, "Elevated ADHD-related screening signal");
  assert.match(result.signal.modifier, /overlapping factors/i);
  assert.deepEqual(result.overlapFactors, responses.overlappingFactors);
}

function testSafetyFlag() {
  const responses = buildBaseResponses(4);
  responses.safetyImmediateRisk = "yes";
  responses.crossSettings = ["Work or school", "Home responsibilities"];
  const result = scoreScreening(responses);
  assert.equal(result.signal.label, "Inconclusive / more context needed");
  assert.equal(result.safetyFlag, true);
}

function testReportDisclaimer() {
  const responses = buildBaseResponses(4);
  responses.crossSettings = ["Work or school", "Home responsibilities"];
  const result = scoreScreening(responses);
  const report = buildMarkdownReport(responses, result);
  assert.match(
    report,
    /This is a self-report summary generated by Vincent ADHD\. It is not a diagnosis, treatment plan, medication recommendation, or substitute for professional evaluation\./
  );
}

function testReportAvoidsDiagnosticClaims() {
  const responses = buildBaseResponses(4);
  responses.crossSettings = ["Work or school", "Home responsibilities"];
  const result = scoreScreening(responses);
  const report = buildMarkdownReport(responses, result);
  assert.doesNotMatch(report, /you have ADHD/i);
  assert.doesNotMatch(report, /meet DSM/i);
  assert.doesNotMatch(report, /medication recommended/i);
}

testLowSignal();
testElevatedSignal();
testNoElevatedWithoutImpairment();
testOverlapCaution();
testSafetyFlag();
testReportDisclaimer();
testReportAvoidsDiagnosticClaims();

console.log("Scoring and report tests passed.");
